name: Testim E2E
on: [push]

jobs:
    run-testimio-cli:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                node-version: 'v24.13.0'
                # You can also change 'lts' to any supported LTS Node.js version.
            - run: npm install -g @testim/testim-cli
            - run: testim --token "FbRwDodQGe0fmK7kfbySfQkH4hcGCY3OXQSEhkHvo44HRGV1DL" --project "5o34e3giDMkFw4u6R2Ef" --grid "testim-ha-grid" --branch "Mohan" --suite "Demo_Run_Testdata"
